config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root to: 'home#index'

  resources :products
  resources :suppliers
  resources :stores
  resources :invoices
  resources :warehouses, except: :index


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/invoice.rb
class Invoice < ApplicationRecord

  validates :status, :sum, presence: true
  validates :sum, numericality: { greater_than_or_equal_to: 0, less_than: 1_000_000 }

  # Do we need category?
  enum status: { 'Не оплачена': 0, 'Оплачена': 1 }

  belongs_to :supplier
  belongs_to :store
  belongs_to :user

end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, :count, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0, less_than: 1_000_000 }
  validates :count, numericality: { greater_than_or_equal_to: 0, less_than: 1_000_000 }

  belongs_to :supplier, optional: true
  belongs_to :store
  belongs_to :invoice, optional: true

end

app/models/store.rb
class Store < ApplicationRecord

  validates :name, :address, presence: true
  validates :name, uniqueness: true

  enum status: { active: 0, closed: 1 }

  has_many :products, dependent: :nullify

end

app/models/supplier.rb
class Supplier < ApplicationRecord

  validates :name, presence: true
  validates :name, uniqueness: true

  enum status: { active: 0, fact: 1, bo: 2, archived: 3 }

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, :role, :first_name, :last_name, presence: true
  validates :email, uniqueness: true

  enum role: { worker: 0, admin: 1 }

  has_many :invoices, dependent: :nullify

end

app/models/warehouse.rb
class Warehouse < ApplicationRecord

  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[role first_name last_name phone_number])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index; end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_action :set_invoice, only: %i[show update edit]

  def index
    @invoices = Invoice.all
  end

  def show; end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoice_params)

    if @invoice.save
      flash[:notice] = 'Invoice has been created'
      redirect_to invoice_path(@invoice)
    else
      flash[:alert] = @invoice.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit; end

  def update
    if @invoice.update(invoice_params)
      flash[:notice] = 'Invoice has been updated'
      redirect_to invoice_path(@invoice)
    else
      flash[:alert] = @invoice.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @invoice.destroy
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def invoice_params
    params.required(:invoice).permit(:id, :supplier_id, :user_id, :store_id, :comment, :status, :sum)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: %i[show update edit]

  def index
    @products = Product.all
  end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = 'Product has been created'
      redirect_to product_path(@product)
    else
      flash[:alert] = @product.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      flash[:notice] = 'Product has been updated'
      redirect_to product_path(@product)
    else
      flash[:alert] = @product.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @product.destroy
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.required(:product).permit(:id, :name, :count, :price, :supplier_id, :store_id, :invoice_id)
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  before_action :set_store, only: %i[show update edit]

  def index
    @stores = Store.all
  end

  def show; end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)

    if @store.save
      flash[:info] = 'Store has been created'
      redirect_to store_path(@store)
    else
      flash[:alert] = @store.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit; end

  def update
    if @store.update(store_params)
      flash[:info] = 'Store has been updated'
      redirect_to store_path(@store)
    else
      flash[:alert] = @store.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @store.destroy
  end

  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.required(:store).permit(:id, :name, :address, :phone_number, :status)
  end

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController

  before_action :set_supplier, only: %i[show update edit]

  def index
    @suppliers = Supplier.all
  end

  def show; end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      flash[:notice] = 'Supplier has been created'
      redirect_to supplier_path(@supplier)
    else
      flash[:alert] = @supplier.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit; end

  def update
    if @supplier.update(supplier_params)
      flash[:notice] = 'Supplier has been updated'
      redirect_to supplier_path(@supplier)
    else
      flash[:alert] = @supplier.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @supplier.destroy
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.required(:supplier).permit(:id, :name, :address, :phone_number, :status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: %i[show update edit]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'User was created'
      redirect_to user_path(@user)
    else
      flash[:alert] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'User was updated'
      redirect_to user_path(@user)
    else
      flash[:alert] = @user.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @user.destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.required(:user).permit(:id, :first_name, :last_name, :role)
  end

end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController

  before_action :set_warehouse, only: %i[show update edit]

  def show; end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)

    if @warehouse.save
      flash[:notice] = 'warehouse has been created'
      redirect_to warehouse_path(@warehouse)
    else
      flash[:alert] = @warehouse.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit; end

  def update
    if @warehouse.update(warehouse_params)
      flash[:notice] = 'Warehouse has been updated'
      redirect_to warehouse_path(@warehouse)
    else
      flash[:alert] = @warehouse.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @warehouse.destroy
  end

  private

  def set_warehouse
    @warehouse = Warehouse.find(params[:id])
  end

  def warehouse_params
    params.required(:warehouse).permit(:id, :name, :address, :phone_number, :money_balance, :status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section class="hero-section text-center py-5">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6">
        <h1 class="display-4 font-weight-bold" style="font-family: Arial, sans-serif; color: #333; letter-spacing: 2px;">Лучший помощник для управления твоим бизнесом</h1>
        <p class="lead my-4"><span class="business-helper">Business helper</span> поможет тебе вести учет твоего товара и магазинов, так что ты сможешь сможешь сфокусироваться на том, что действительно имеет значение.</p>
        
        <% if user_signed_in? %>
          <%= link_to "Начать", products_path, class: "btn btn-primary btn-lg" %>
        <% else %>
          <%= link_to "Начать", new_user_session_path, class: "btn btn-primary btn-lg" %>
        <% end %>

      </div>
      <div class="col-md-6">
        <%= image_tag("big_logo.png", class: 'img-fluid rounded-circle shadow-lg') %>

 
        <%# <img class="img-fluid rounded-circle shadow-lg" src="/tmp/big_logo.png" alt="Big Logo"> %>
      </div>
    </div>
  </div>
</section>

<section class="features-section py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-3">
          <i class="fas fa-chart-line fa-3x text-primary"></i>
          <div class="card-body">
            <h5 class="card-title text-uppercase text-primary">Аналитика</h5>
            <p class="card-text">Получите представление о своем бизнесе с помощью наших мощных инструментов аналитики.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-3">
          <i class="fas fa-store fa-3x text-primary"></i>
          <div class="card-body">
            <h5 class="card-title text-uppercase text-primary">Магазины</h5>
            <p class="card-text">Управляйте своими магазинами и запасами с легкостью.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-3">
          <i class="fas fa-boxes fa-3x text-primary"></i>
          <div class="card-body">
            <h5 class="card-title text-uppercase text-primary">Товары</h5>
            <p class="card-text">Упорядочивайте и отслеживайте свои товары с помощью нашей простой в использовании системы.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="cta-section py-5 text-center">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2 class="text-uppercase font-weight-bold">Вы готовы вывести свой бизнес на новый уровень?</h2>
      </div>
      <div class="col-md-6">
        <% if user_signed_in? %>
          <%= link_to "Начать", products_path, class: "btn btn-primary btn-lg" %>
        <% else %>
          <%= link_to "Начать", new_user_session_path, class: "btn btn-primary btn-lg" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/invoices/edit.html.erb
<div class="container">
  <h3><%= "Редактировать накладную № #{@invoice.id} (от From to To)" %></h3>

  <%= render 'form' %>

</div>

app/views/invoices/index.html.erb
<div class="container">
  <h2>Список накладных</h2>
  <table class="table table-tr-hover">
    <thead>
      <tr>
         <td class="py-3 px-4">Номер</th>
         <td class="py-3 px-4">Сумма</th>
         <td class="py-3 px-4">Поставщик</th>
         <td class="py-3 px-4">Магазин</th>
         <td class="py-3 px-4">Действия</th>
      </tr>
    </thead>
    <tbody>
      <% @invoices.each do |invoice| %>
        <tr>
          <td class="py-3 px-4 table-cell"><%= link_to invoice.id, invoice_path(invoice), class: 'table-link' %></td>
          <td class="py-3 px-4 table-cell"><%= number_to_currency(invoice.sum) %></td>
          <td class="py-3 px-4 table-cell"><%= link_to invoice.supplier.name&.capitalize, supplier_path(invoice.supplier), class: 'table-link' %></td>
          <td class="py-3 px-4 table-cell"><%= link_to invoice.store.name&.capitalize, store_path(invoice.store), class: 'table-link' %></td>
          <td>
            <%= link_to 'Обновить', edit_invoice_path(invoice), class: 'btn btn-sm btn-primary mr-2' %>
            <%= link_to 'Удалить', invoice, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Создать накладную', new_invoice_path, class: 'btn btn-primary mr-2' %>

</div>

app/views/invoices/new.html.erb
<div class="container">
  <h3>Создать накладную</h3>

  <%= render 'form' %>

</div>

app/views/invoices/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h2><%= "Накладная №#{@invoice.id}, поставщик #{@invoice.supplier.name&.capitalize}, в магазин #{@invoice.store.name&.capitalize}"  %></h2>
      <hr>
      
      <h5>Сумма:</h5>
      <p><%= @invoice.sum %></p>
      
      <h5>Комментарий:</h5>
      <p><%= @invoice.comment %></p>
      
      <h5>Магазин:</h5>
      <p><%= link_to @invoice.store.name.capitalize, store_path(@invoice.store) %></p>

      <h5>Поставщик:</h5>
      <p><%= link_to @invoice.supplier.name&.capitalize, store_path(@invoice.store) %></p>
      
      <h5>Статус:</h5>
      <p><%= @invoice.status %></p>

      <div class="text-center">
        <%= link_to 'Изменить', edit_invoice_path(@invoice), class: "btn btn-primary" %>
        <%= link_to 'Назад', invoices_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BusinessHelper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href=<%= root_path %>><%= image_tag("small_logo.png", class: 'navbar-logo') %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to 'Склад', '#', class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Магазины', stores_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Накладные', invoices_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Поставщики', suppliers_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Товары', products_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto"></ul>
        <%= form_tag('#', method: :get, class: 'form-inline my-2 my-lg-0') do %>
          <div class="input-group">
            <%= text_field_tag :search, params[:search], class: 'form-control mr-sm-2', placeholder: 'Search' %>
            <span class="input-group-btn">
              <%= button_tag type: :submit, class: 'btn btn-outline-success my-2 my-sm-0' do %>
                <i class="fas fa-search"></i>
              <% end %>
            </span>
          </div>
        <% end %>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <% if key == "notice" %>
        <div id="notice-alert" class="alert alert-success 1alert-dismissible fade show" style='text-align: center;' role="alert">
          <%= value %>
        </div>
      <% elsif key == "alert" %>
        <div id="alert-alert" class="alert alert-danger alert-dismissible fade show" style='text-align: center;' role="alert">
          <%= value %>
        </div>
      <% end %>
    <% end %>
    
    <%= yield %>

    <footer class="bg-light py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-4 mb-4">
            <h4>О нас</h4>
            <p>Профессиональная разработка сайтов</p>
          </div>
          <div class="col-md-4 mb-4">
            <h4>Контакты</h4>
            <ul class="list-unstyled">
              <li>Телефон: +34 666 131 937</li>
              <li>Email: info@example.com</li>
              <li>Адрес: г. Валенсия, ул. Примерная, д. 1</li>
            </ul>
          </div>
          <div class="col-md-4 mb-4">
            <h4>Подписка на новости</h4>
            <form>
              <div class="form-group">
                <label for="inputEmail">Введите ваш email:</label>
                <input type="email" class="form-control" id="inputEmail" placeholder="Email">
              </div>
              <button type="submit" class="btn btn-primary">Подписаться</button>
            </form>
          </div>
        </div>
        <hr>
        <p class="text-center">&copy; 2023 My Company. Все права защищены.</p>
      </div>
    </footer>
    
  </body>
</html>

<script>
  var noticeAlert = document.getElementById("notice-alert");
  var alertAlert = document.getElementById("alert-alert");

  if (noticeAlert) {
    setTimeout(function() {
      noticeAlert.classList.add("fade-out");
    }, 2000);
  }

  if (alertAlert) {
    setTimeout(function() {
      alertAlert.classList.add("fade-out");
    }, 2000);
  }
</script>

app/views/products/edit.html.erb
<div class="container">
  <h3><%= "Редактировать товар #{@product.name&.capitalize}" %></h3>

  <%= render 'form' %>

</div>

app/views/products/index.html.erb
<div class="container">
  <h2>Все продукты</h2>
  <table class="table table-tr-hover">
    <thead>
      <tr>
         <td class="py-3 px-4">Имя</th>
         <td class="py-3 px-4">Цена</th>
         <td class="py-3 px-4">Количество</th>
         <td class="py-3 px-4">Магазин</th>
         <td class="py-3 px-4">Поставщик</th>
         <td class="py-3 px-4">Действия</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td class="py-3 px-4 table-cell"><%= link_to product.name.capitalize, product_path(product), class: 'table-link' %></td>
          <td class="py-3 px-4 table-cell"><%= number_to_currency(product.price) %></td>
          <td class="py-3 px-4 table-cell"><%= product.count %></td>
          <td class="py-3 px-4 table-cell"><%= link_to product.store.name&.capitalize, store_path(product.store), class: 'table-link' %></td>
          <td class="py-3 px-4 table-cell"><%= link_to product.supplier.name&.capitalize, supplier_path(product.supplier), class: 'table-link' %></td>
          <td>
            <%= link_to 'Обновить', edit_product_path(product), class: 'btn btn-sm btn-primary mr-2' %>
            <%= link_to 'Удалить', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Создать', new_product_path, class: 'btn btn-primary mr-2' %>

</div>

app/views/products/new.html.erb
<div class="container">
  <h3>Добавить новый продукт</h3>

  <%= render 'form' %>

</div>

app/views/products/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h2><%= @product.name.capitalize%></h2>
      <hr>
      <h5>Название:</h5>
      <p><%= @product.name.capitalize %></p>

      <h5>Цена:</h5>
      <p><%= number_to_currency(@product.price) %></p>

      <h5>Количеств:</h5>
      <p><%= @product.count %></p>

      <h5>Магазин:</h5>
      <p><%= link_to @product.store.name.capitalize, store_path(@product.store) %></p>

      <h5>Поставщик:</h5>
      <p><%= link_to @product.supplier.name&.capitalize, store_path(@product.store) %></p>

      <div class="text-center">
        <%= link_to 'Изменить', edit_product_path(@product), class: "btn btn-primary" %>
        <%= link_to 'Назад', products_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/stores/edit.html.erb
<div class="container">
  <h3><%= "Редактировать магазин #{@store.name&.capitalize}" %></h3>

  <%= render 'form' %>

</div>

app/views/stores/index.html.erb
<div class="container">
  <h2>Все магазины</h2>
  <table class="table table-tr-hover">
    <thead>
      <tr>
         <td class="py-3 px-4">Имя</th>
         <td class="py-3 px-4">Адрес</th>
         <td class="py-3 px-4">Номер телефона</th>
         <td class="py-3 px-4">Статус</th>
         <td class="py-3 px-4">Действия</th>
      </tr>
    </thead>
    <tbody>
      <% @stores.each do |store| %>
        <tr>
          <td class="py-3 px-4 table-cell"><%= link_to store.name.capitalize, store_path(store), class: 'table-link' %></td>
          <td class="py-3 px-4 table-cell"><%= store.address %></td>
          <td class="py-3 px-4 table-cell"><%= store.phone_number %></td>
          <td class="py-3 px-4 table-cell"><%= store.status %></td>
          <td>
            <%= link_to 'Обновить', edit_store_path(store), class: 'btn btn-sm btn-primary mr-2' %>
            <%= link_to 'Удалить', store, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Создать', new_store_path, class: 'btn btn-primary mr-2' %>

</div>

app/views/stores/new.html.erb
<div class="container">
  <h3>Добавить новый магазин</h3>

  <%= render 'form' %>

</div>

app/views/stores/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h2><%= @store.name&.capitalize %></h2>
      <hr>
      <h5>Адрес:</h5>
      <p><%= @store.address %></p>
      <h5>Номер телефона:</h5>
      <p><%= @store.phone_number %></p>
      <h5>Статус:</h5>
      <p><%= @store.status %></p>
      <div class="text-center">
        <%= link_to 'Изменить', edit_store_path(@store), class: "btn btn-primary" %>
        <%= link_to 'Назад', stores_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/suppliers/index.html.erb
<div class="container">
  <h2>Все поставщики</h2>
  <table class="table table-tr-hover">
    <thead>
      <tr>
         <td class="py-3 px-4">Имя</th>
         <td class="py-3 px-4">Адрес</th>
         <td class="py-3 px-4">Номер телефона</th>
         <td class="py-3 px-4">Статус</th>
         <td class="py-3 px-4">Действия</th> 
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td class="py-3 px-4 table-cell"><%= link_to supplier.name.capitalize, supplier_path(supplier), class: 'table-link' %></td>
          <td class="py-3 px-4 table-cell"><%= supplier.address %></td>
          <td class="py-3 px-4 table-cell"><%= supplier.phone_number %></td>
          <td class="py-3 px-4 table-cell"><%= supplier.status %></td>
          <td>
            <%= link_to 'Обновить', edit_supplier_path(supplier), class: 'btn btn-sm btn-primary mr-2' %>
            <%= link_to 'Удалить', supplier, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <%= link_to 'Создать', new_supplier_path, class: 'btn btn-primary mr-2' %>

</div>

app/views/suppliers/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h2><%= @supplier.name&.capitalize %></h2>
      <hr>
      <h5>Адрес:</h5>
      <p><%= @supplier.address %></p>
      <h5>Номер телефона:</h5>
      <p><%= @supplier.phone_number %></p>
      <h5>Статус:</h5>
      <p><%= @supplier.status %></p>
      <div class="text-center">
        <%= link_to 'Изменить', edit_supplier_path(@supplier), class: "btn btn-primary" %>
        <%= link_to 'Назад', suppliers_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2>Все пользователи</h2>
  <table class="table table-tr-hover">
    <thead>
      <tr>
         <td class="py-3 px-4">Имя</th>
         <td class="py-3 px-4">Почта</th>
         <td class="py-3 px-4">Роль</th>
         <td class="py-3 px-4">Действия</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="py-3 px-4 table-cell"><%= link_to "#{user.first_name&.capitalize} #{user.last_name&.capitalize}", user_path(user), class: "table-link" %></td>
          <td class="py-3 px-4 table-cell"><%= link_to user.email, user_path(user), class: "table-link" %></td>
          <td class="py-3 px-4 table-cell"><%= link_to user.role, user_path(user), class: "table-link" %></td>
          <td class="">
            <%= link_to 'Обновить', edit_user_path(user), class: 'btn btn-sm btn-primary mr-2' %>
            <%= link_to 'Удалить', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Создать', new_user_path, class: 'btn btn-primary mr-2' %>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h2><%= "#{@user.first_name&.capitalize} #{@user.last_name.capitalize}"%></h2>
      <hr>
      <h5>Почта:</h5>
      <p><%= @user.email %></p>
      <h5>Роль:</h5>
      <p><%= @user.role %></p>

      <div class="text-center">
        <%= link_to 'Изменить', edit_user_path(@user), class: "btn btn-primary" %>
        <%= link_to 'Назад', users_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/warehouses/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h2><%= @warehouse.name&.capitalize %></h2>
      <hr>
      <h5>Адрес:</h5>
      <p><%= @warehouse.address %></p>
      <h5>Номер телефона:</h5>
      <p><%= @warehouse.phone_number %></p>
      <h5>Статус:</h5>
      <p><%= @warehouse.status %></p>
      <div class="text-center">
        <%= link_to 'Изменить', edit_warehouse_path(@warehouse), class: "btn btn-primary" %>
        <%= link_to 'Назад', warehouses_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>